[
  {
    nome: 'Solange Estudante',
    email: 'solange@email.com',
    cpf: '63058133022',
    ativo: true,
    role: 'estudante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nome: 'Igor Estudante',
    email: 'igor@email.com',
    cpf: '99018205028',
    ativo: true,
    role: 'estudante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nome: 'Aline Estudante',
    email: 'aline@email.com',
    cpf: '92797497066',
    ativo: true,
    role: 'estudante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nome: 'Fernando Estudante',
    email: 'fernando@email.com',
    cpf: '17195730000',
    ativo: true,
    role: 'estudante',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nome: 'Ricardo Docente',
    email: 'ricardo@email.com',
    cpf: '06946507061',
    ativo: true,
    role: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nome: 'Dine Docente',
    email: 'dine@email.com',
    cpf: '80941142078',
    ativo: true,
    role: 'docente',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
